MALE = 'male'
FEMALE = 'female'
HERMAPHRODITE = 'hermaphrodite'
NA = 'n/a'

BLACK = 'black'
BROWN = 'brown'
BLONDE = 'blonde'
RED = 'red'
WHITE = 'white'
BALD = 'bald'
YELLOW = 'yellow'
GREEN = 'green'
PURPLE = 'purple'
UNKNOWN = 'unknown'
